
//LA FUNCION SUMA RECIBIRA LOS DOS NUMEROS INGRESADOS POR EL USUARIO Y LOS SUMARA, RETORNARA EL RESULTADO DE ESA SUMA
float suma(float numero1, float numero2);

//LA FUNCION RESTA RECIBIRA LOS DOS NUMEROS INGRESADOS POR EL USUARIO Y LOS RESTARA, RETORNARA EL RESULTADO DE ESA RESTA
float resta(float numero1, float numero2);

//LA FUNCION DIVISION RECIBIRA LOS DOS NUMEROS INGRESADOS POR EL USUARIO Y LOS DIVIDIRA, RETORNARA EL RESULTADO DE ESA DIVISION
float division(float numero1, float numero2);

//LA FUNCION MULTIPLICACION RECIBIRA LOS DOS NUMEROS INGRESADOS POR EL USUARIO Y LOS MULTIPLICARA, RETORNARA EL RESULTADO DE ESA MULTIPLICACION
float multiplicacion(float numero1, float numero2);

//LA FUNCION FACTORIZACION RECIBIRA UN NUMERO Y CALCULARA EL FACTORIAL DE ESE NUMERO, RETORNARA EL RESULTADO DE ESA FACTORIZACION
int factorizacion(float numero);

/*LA FUNCION MOSTRAR RESULTADOS RECIBIRA LOS RESULTADOS DE TODAS LAS OPERACIONES MATEMATICAS Y SUS DEBIDAS VALIDACIONES
 Y LOS MOSTRARA TODOS LLAMANDO A CADA FUNCION PERZONALIDA PARA CADA RESULTADO*/
void mostrarResultados(float respuestaSuma, int validacionSuma, float respuestaResta, int validacionResta, float respuestaDivision, int validacionDivision, float respuestaMultiplicacion, int validacionMultiplicacion, int respuestaFactorialUno, int validacionFactorialUno, int respuestaFactorialDos, int validacionFactorialDos);

//LA FUNCION RECIBIRA LA SUMA Y LA VALIDACION, MOSTRARA EL RESULTADO DE LA SUMA SI ESTA VALIDADA, DE LO CONTRARIO MOSTRARA ERROR
void mostrarSuma(float respuestaSuma, int validacionSuma);

//LA FUNCION RECIBIRA LA RESTA Y LA VALIDACION, MOSTRARA EL RESULTADO DE LA RESTA SI ESTA VALIDADA, DE LO CONTRARIO MOSTRARA ERROR
void mostrarResta(float respuestaResta, int validacionResta);

//LA FUNCION RECIBIRA LA DIVISION Y LA VALIDACION, MOSTRARA EL RESULTADO DE LA DIVISION SI ESTA VALIDADA, DE LO CONTRARIO MOSTRARA ERROR
void mostrarDivision(float respuestaDivision, int validacionDivision);

//LA FUNCION RECIBIRA LA MULTIPLICACION Y LA VALIDACION, MOSTRARA EL RESULTADO DE LA MULTIPLICACION SI ESTA VALIDADA, DE LO CONTRARIO MOSTRARA ERROR
void mostrarMultiplicacion(float respuestaMultiplicacion, int validacionMultiplicacion);

//LA FUNCION RECIBIRA LA FACTORIZACION Y LA VALIDACION, MOSTRARA EL RESULTADO DE LA FACTORIZACION SI ESTA VALIDADA, DE LO CONTRARIO MOSTRARA ERROR
void mostrarFactorialUno(int respuestaFactorialUno, int validacionFactorialUno);

//LA FUNCION RECIBIRA LA FACTORIZACION Y LA VALIDACION, MOSTRARA EL RESULTADO DE LA FACTORIZACION SI ESTA VALIDADA, DE LO CONTRARIO MOSTRARA ERROR
void mostrarFactorialUno(int respuestaFactorialDos, int validacionFactorialDos);

